# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='people',
        ),
    ]
