# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-04 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_auto_20171004_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
