# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0010_auto_20171010_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='email',
            new_name='emailid',
        ),
        migrations.RemoveField(
            model_name='people',
            name='id',
        ),
        migrations.AddField(
            model_name='people',
            name='user_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1),
        ),
        migrations.AlterModelTable(
            name='people',
            table='person',
        ),
    ]
