# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0011_auto_20171017_2030'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='people',
            table='people',
        ),
    ]
