# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0014_auto_20171017_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'managed': False},
        ),
    ]
