# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0020_auto_20171031_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
