# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0021_auto_20171103_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False},
        ),
    ]
