# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 12:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0022_auto_20171103_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(max_length=8)),
                ('work', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-zA-Z, ]*$', 'Only alphabetic characters are allowed.')])),
                ('university', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-zA-Z, ]*$', 'Only alphabetic characters are allowed.')])),
                ('languages', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-zA-Z, ]*$', 'Only alphabetic characters are allowed.')])),
                ('hobbies', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('^[a-zA-Z, ]*$', 'Only alphabetic characters are allowed.')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
