# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0023_personprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personprofile',
            table='profile',
        ),
    ]
