# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0024_auto_20171103_1743'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
